### ISSUE TITLE
安装 推荐开发者模式是什么? clone后安装无效

### ISSUE THREAD

**Issue by blackScroip0093** [banxi1988/iOSCodeGenerator#1]

**Comment by blackScroip0093** [comment]
Installed /Library/Python/2.7/site-packages/MarkupSafe-1.0-py2.7-macosx-10.11-intel.egg
Finished processing dependencies for ios-code-generator==1.0.0 终端是提示成功的

**Comment by blackScroip0093** [comment]
运行脚本提示    操作“运行 Shell 脚本”时出现错误。

**Comment by blackScroip0093** [comment]
解决了 . 终端又装了次就好了,可能第一次装好的被删掉了

**Comment by banxi1988** [comment]
感谢使用, 有什么不明白的地方,欢迎多提 issue.
