### ISSUE TITLE
会报错

### ISSUE THREAD

**Issue by Joneze** [banxi1988/iOSCodeGenerator#2]
可能你描述的比较简单，我根据你的方法先通过开发者模式安装了py脚本，然后拷贝sevices内的文件到本机文件夹内。然后 再根据你的gif 动图来执行脚本的时候报错，如图

![image](https://user-images.githubusercontent.com/10105290/33259517-14abc912-d398-11e7-9b39-cfb3c6e37c31.png)

**Comment by banxi1988** [comment]
@Joneze 从上面的错误提示来是 Json解析错误.
你可以先检查一下你的 Json 数据格式是否正确. (Invalid control character 非法控制字符 ?)
或者把数据发上来,我测试一下看看.

**Comment by Joneze** [comment]
我分别试了嵌套字典的 和不嵌套的，都报这个错。

{
    "id" : 409727,
    "title" : "为什么 Linux 得 shell 不直接使用 JavaScript 的语法",
    "url" : "http://www.v2ex.com/t/409727",
    "content" : "另起炉灶有意思吗",
    "content_rendered" : "\u003Cp\u003E另起炉灶有意思吗\u003C/p\u003E\u000A",
    "replies" : 108,
    "member" : {
        "id" : 254032,
        "username" : "86322989",
        "tagline" : "",
        "avatar_mini" : "//v2ex.assets.uxengine.net/avatar/838b/31da/254032_mini.png?m=1507543878",
        "avatar_normal" : "//v2ex.assets.uxengine.net/avatar/838b/31da/254032_normal.png?m=1507543878",
        "avatar_large" : "//v2ex.assets.uxengine.net/avatar/838b/31da/254032_large.png?m=1507543878"
    },
    "node" : {
        "id" : 11,
        "name" : "linux",
        "title" : "Linux",
        "title_alternative" : "Linux",
        "url" : "http://www.v2ex.com/go/linux",
        "topics" : 3729,
        "avatar_mini" : "//v2ex.assets.uxengine.net/navatar/6512/bd43/11_mini.png?m=1511095631",
        "avatar_normal" : "//v2ex.assets.uxengine.net/navatar/6512/bd43/11_normal.png?m=1511095631",
        "avatar_large" : "//v2ex.assets.uxengine.net/navatar/6512/bd43/11_large.png?m=1511095631"
    },
    "created" : 1511704130,
    "last_modified" : 1511771913,
    "last_touched" : 1511773044
}

**Comment by banxi1988** [comment]
@Joneze 已经修正了对应问题. 见提交 https://github.com/banxi1988/iOSCodeGenerator/commit/c3dd6d4b7d30c7438328a65204e2dbe8ff4cd996

另外一个问题的话,你上面的这个数据内部有嵌套的话,需要单独处理.
因为可能重复引用的问题,所以嵌套需要单独处理.
